### ISSUE TITLE
Item usability issue?

### ISSUE THREAD

**Issue by Frenzgyn** [The-Gate-Project/DarkHorizons#10]
I noticed it a while ago (before DarkHorizons was adopted by The Gate Project) but it is not fixed yet: 
Helm of Health behave oddly: it isn't usable by unkitted classes  (Fighters, paladins, rangers...) while it works for their kits.

The problem is in the "generalist" tag, that is more a "trueclass" tag which prevents unkitted class (or multi-class) from using the specific item (https://forums.beamdog.com/discussion/82119/generalist-mage-flag).

Not tested in game, but looking in NI here are the other items affected:

CMHELM01.itm
CMHELM02.itm
CMHELM03.itm
CMHELM04.itm
CMLEAT2.itm
CMLEAT3.itm
CMLEAT4.itm
CMLEAT5.itm
CMLEAT6.itm
CMLUTE.itm
CMPLAT11.itm
CMSHLD01.ITM
CMSHLD03.ITM
CMSHLD04.itm
CMSHLD05.itm
CMSHQ01.itm
CMSHQ02.itm
mabrac01.itm
MAFORG06.ITM
MAHELM01.ITM
MAHELM02.ITM (The aforementioned Helm of Health)
mapla001.itm
maplat02.itm
mashld01.itm
mclck01.itm
mplat01.itm

**Comment by 11jo** [comment]
Noted, a review of items restrictions and effects is planned, but I keep reporting..

Roberciiik is currently preparing the various forks with a view to bringing them together.
Once this is done, we'll be able to check the items.
Your list will be useful for restrictions and Autodescritpion will probably be used to check effects.

If you wish to provide a Pull request yourself, no problem.

To see if Roberccik has anything to say.

**Comment by Roberciiik** [comment]
I haven't started merging branches process yet. However, I agree that it would be better to update items after combining all versions into one. I will prioritize this work then to not block you.

**Comment by 11jo** [comment]
No pressure, take your time. (And thanks for your work by the way, on this and on the worldmap)

**Comment by Frenzgyn** [comment]
Thanks for the reply, I'll update the message if I will find anything else. 
Btw, the mod was in this state for years, so no hurry, it could wait a bit more :)

**Comment by 11jo** [comment]
Hello, I've started checking the items, it'll take a while... (28/ 261)

In the meantime, the last commit correct the usability issues for the mentionned items, if you want to take a look @Frenzgyn, It was really tedious, so inattention errors are possible.

**Comment by 11jo** [comment]
@Frenzgyn, not sure if you saw the previous post but if there is nothing to add I will close the issue in a few days.

**Comment by Frenzgyn** [comment]
Yeah, sorry I did not have the time to check things, close the issues, no problem.
