### ISSUE TITLE
After EET install fails with translation error

### ISSUE THREAD

**Issue by bouncer1798** [The-Gate-Project/DarkHorizons#17]
I downloaded the latest master zip and tried installing it after EET but got the following error:

[DarkHorizons/items/cmtck01.itm] loaded, 402 bytes
ERROR: No translation provided for @902
ERROR: [DarkHorizons/items/cmtck01.itm] -> [override/cmtck01.itm] Patching Failed (COPY) (Not_found)

Attached is a weidu log file and setup.debug file.

[WeiDU.log](https://github.com/The-Gate-Project/DarkHorizons/files/14936605/WeiDU.log)
[SETUP-DARKHORIZONS.log](https://github.com/The-Gate-Project/DarkHorizons/files/14936613/SETUP-DARKHORIZONS.log)

I have zero knowledge of IE modding but from the setup.debug file it looks to me like it is using the wrong translation file. The setup-ee.tra file has a 902 entry but the normal setup.tra file doesn't.

**Comment by Roberciiik** [comment]
Current master branch is experimental so there might be some issues when installing. I will look at it at the weekend or something.

As a workaround you can try to copy all the missing lines from setup-ee.tra to setup.tra if this helps.

**Comment by 11jo** [comment]
Hello !

By adding bg2ee next to bgee **bg2ee** eet [in this line](https://github.com/The-Gate-Project/DarkHorizons/blob/1f13ad522234d1744e0158b112136726c42f82da/DarkHorizons/Setup-DarkHorizons.tp2#L45) the installation proceeds. If it helps in the meantime.

**Comment by bouncer1798** [comment]
Goodness you guys respond fast. Thanks adding **bg2ee** on line 45 worked. You guys are awesome
