### ISSUE TITLE
CMHAMM01.ITM - War Hammer +3 Asgrim's Fate - strength bonus flag is not set

### ISSUE THREAD

**Issue by lulnope** [The-Gate-Project/DarkHorizons#27]
This is not mentioned in description of the item. Either set the flag or add mention in item description. I'm not sure which action is suitable.

**Comment by 11jo** [comment]
Not sure about what to do about it.

Since it's already a +3 weapon in bgee.

**Comment by 11jo** [comment]
I have added the modified items (Set strength bonus flag).

the alternative would be to modify descriptions for all languages...

They will be added in the next commit (in a few days with unrelated other fixes)

And thanks for the reports !

**Comment by lulnope** [comment]
If you set the bonus flag maybe also increase the price to something really high.

CMHAMM02.ITM is also available at the same merchant and it is much worse despite having the same +3 enchantment but MUCH worse stats & MUCH higher price. Maybe set CMHAMM01.ITM - War Hammer +3 Asgrim's Fate price to something like 20k or 25k so that it's power is appropriately reflected in price.

**Comment by lulnope** [comment]
> And thanks for the reports !
no. thank you for the mod and it's maintenance.

**Comment by 11jo** [comment]
I didn't touch store price (yet ?).

And I am not sure I will since it's not really up to me, (we still hope for Com_Solaufein to come back...)

But it's possible that one day something will be done about it.

Anyway, I'm going to look at this particular item and probably follow your advice, as it doesn't make sense that the price is higher.

**Comment by 11jo** [comment]
With a charisma of 14, here is the new prices for CMHAMM01 (Asgrim's Fate) et CMHAMM03 (War Hammer +2 + 1d4 fire damages)

It's not perfect, but it's still equivalent to the other prices, of course each of them should be more expensive.

![price](https://github.com/user-attachments/assets/6cd4209e-783f-425a-9249-b29106d75c43)

**Comment by lulnope** [comment]
Great. Prices make sense now. That War Hammer+2 was weirdly expensive compared to other two hammers despite lower enchantment.  Large War Hammer +3 and Asgrim's Fate +3 were way too cheap for a +3 hammers. Now they seem reasonable.

**Comment by 11jo** [comment]
This issue will be closed when the changes will be merged. (You will therefore be informed when they are implemented)

Thanks for your time !
