### ISSUE TITLE
CMLEAT4.ITM - Assassin's armor - unusable by trueclass thief

### ISSUE THREAD

**Issue by lulnope** [The-Gate-Project/DarkHorizons#28]
I'm not sure if this is intended but [CMLEAT4.ITM - Assassin's armor] is usable by dual class thief like thief/mage Imoen and not usable by single trueclass thief like Safana. Unsuable by Generalist flag is set on the item.

I'm not sure what action is suitable - to disallow multi/dual-class thiefs to use the item or to allow trueclass thief to use but current state is confusing.

**Comment by 11jo** [comment]
This one should be corrected for the master. (I have reviewed all the items in the two past months)

Until a new version is released I encourage you to use the master.
